# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       qtconfiguration

# >> macros
# << macros

Summary:    Qt Configuration library.
Version:    5.0.0.20130820.9e22615
Release:    1
Group:      Applications/System
License:    BSD
Source0:    qtconfiguration-%{version}.tar.bz2
BuildRequires:  pkgconfig(Qt5Core)
#BuildRequires:  pkgconfig(Qt5Gui)
#BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(dconf)
BuildRequires:  pkgconfig(dconf-dbus-1)
BuildRequires:  python
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig


%description
Settings API with change notifications.

%package devel
Summary:    Devel files for QtConfiguration
Group:      Development/System
Requires:   %{name} = %{version}-%{release}

%description devel
Devel for QtConfiguration



%prep
%setup -q -n qtconfiguration

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 qtconfiguration.pro
#HERE=`pwd`
#(cd src/xdg; perl -w /usr/lib/qt5/bin/syncqt.pl -check-includes -module QtXdg -version 0.1.0 -outdir $HERE)


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install
rm -f %{buildroot}/%{_libdir}/*.la

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libQt0Configuration.so.0
%{_libdir}/libQt0Configuration.so.0.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/qt5/QtConfiguration/
%{_libdir}/cmake/Qt5Configuration/Qt5Configuration.cmake
%{_libdir}/cmake/Qt5Configuration/Qt5Configuration.cmake
%{_libdir}/libQt0Configuration.prl
%{_libdir}/libQt0Configuration.so
%{_libdir}/pkgconfig/Qt0Configuration.pc
%{_datadir}/qt5/mkspecs/modules/qt_lib_configuration.pri
# >> files
# << files
